builders:
  bloc_codegen:
    target: ':bloc_codegen'
    import: 'package:bloc_codegen_generator/builder.dart'
    builder_factories: ["blocCodegen"]
    build_extensions: {".dart": ["bloc.g.part"]}
    auto_apply: dependents
    build_to: cache
    applies_builders: ["source_gen|combining_builder"]
