name: bloc_codegen_generator
description: A new Flutter package project.
version: 0.0.1
homepage: https://github.com/HelloCore/bloc_codegen

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  build: ^1.2.2
  source_gen: ^0.9.4+2
  code_builder: ^3.2.0
  analyzer: ^0.39.3
  bloc_codegen: ^0.0.1

dev_dependencies:
  source_gen_test: any
  test: ^1.0.0